version: '3'
services:

  postgres:
    image: "jobfit/postgres"
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - SAFEMODE=False
    volumes:
      - ./data/postgres/data:/data

  webapp:
    image: "jobfit/webapp"
    container_name: webapp
    hostname: webapp
    restart: unless-stopped
    environment:
      - SAFEMODE=False
      - DJANGO_DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DJANGO_DB_NAME=jobfit
      - DJANGO_DB_USER=jobfit_master
      - DJANGO_DB_PASSWORD=your_db_password_here
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DEV_SERVER=True
      - DJANGO_DEBUG=True
      - DJANGO_LOG_LEVEL=CRITICAL
      - JOBFIT_LOG_LEVEL=DEBUG
      - MAIN_DOMAIN_NAME=https://jobfit.fyi
      - OPENAI_KEY=your_openai_key_here
      #- DJANGO_SECRET_KEY=your_secret_key_here
      #- DJANGO_EMAIL_HOST=
      #- DJANGO_EMAIL_HOST_USER=
      #- DJANGO_EMAIL_HOST_PASSWORD=
      #- DJANGO_EMAIL_FROM="JobFit <notifications@jobfit.fyi>"
      #- INVITATION_CODE=
    ports:
      - "8080:8080"
      - "7000-7020:7000-7020"
    volumes:
      - ./data/shared:/shared
      - ./data/webapp/data:/data
      - ./data/webapp/log:/var/log/webapp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/webapp/code:/opt/code

  proxy:
    image: "jobfit/proxy"
    container_name: proxy
    hostname: proxy
    restart: unless-stopped
    environment:
      - SAFEMODE=False
      - JOBFIT_HOST=localhost
      - JOBFIT_TASKS_PROXY_HOST=localhost
    ports:
      - "80:80"
      - "443:443"
      - "9000-9020:9000-9020"
      - "5000:5000"
    volumes:
      - ./data/shared:/shared
      - ./data/proxy/letsencrypt:/etc/letsencrypt
      - ./data/proxy/log:/var/log/proxy
