#!/bin/bash

# Example: jobfit/test jobfit.core_app.tests.test_apis.ApiTests.test_api_web_auth

# You probably want to set DJANGO_LOG_LEVEL to ERROR and JOBFIT_LOG_LEVEL to DEBUG if you are doing tdd.
DJANGO_LOG_LEVEL="CRITICAL"
JOBFIT_LOG_LEVEL="CRITICAL"

# Set DB to SQLIte in-memory
DJANGO_DB_ENGINE="django.db.backends.sqlite3"
DJANGO_DB_NAME=":memory:"

jobfit/shell webapp "export DJANGO_DB_ENGINE=$DJANGO_DB_ENGINE && export DJANGO_DB_NAME=$DJANGO_DB_NAME && cd /opt/code && DJANGO_LOG_LEVEL=$DJANGO_LOG_LEVEL JOBFIT_LOG_LEVEL=$JOBFIT_LOG_LEVEL python3 manage.py test $@"
