# Generated by Django 2.2.1 on 2026-04-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20260408_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
