# Generated by Django 2.2.1 on 2026-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_auto_20260408_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
