# Generated by Django 2.2.1 on 2026-04-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_giftcode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scoring_mode',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core_app.CV'),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_notes',
            field=models.BooleanField(default=False),
        ),
    ]
